Repository 1e5i-Shark/algobaro-api, pull requests merged in 2024-03, with the labels that each got.

#72 dev -> main
  src/main/java/ei/algobaroapi/domain/room/domain/Room.java
  src/main/java/ei/algobaroapi/domain/room/dto/request/RoomCreateRequestDto.java
  src/main/java/ei/algobaroapi/domain/room/dto/request/RoomUpdateRequestDto.java
  src/main/java/ei/algobaroapi/domain/room/dto/response/RoomDetailResponseDto.java
  src/main/java/ei/algobaroapi/domain/room/dto/response/RoomResponseDto.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/ProblemControllerDoc.java
Labels: merge

#76 수동 방장 권한 위임 기능 구현
  src/main/java/ei/algobaroapi/domain/room_member/controller/RoomMemberControllerDocImpl.java
  src/main/java/ei/algobaroapi/domain/room_member/domain/RoomMember.java
  src/main/java/ei/algobaroapi/domain/room_member/dto/request/HostChangeRequestDto.java
  src/main/java/ei/algobaroapi/domain/room_member/dto/response/RoomHostResponseDto.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/HostValidationException.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/OrganizerValidationException.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/common/RoomMemberErrorCode.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/common/RoomMemberExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/room_member/service/RoomMemberService.java
  src/main/java/ei/algobaroapi/domain/room_member/service/RoomMemberServiceImpl.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/RoomMemberControllerDoc.java
Labels: feat

#80 dev -> main
  src/main/java/ei/algobaroapi/AlgobaroController.java
  src/main/java/ei/algobaroapi/domain/room/controller/RoomControllerDocImpl.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomService.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomServiceImpl.java
  src/main/java/ei/algobaroapi/domain/room_member/controller/RoomMemberControllerDocImpl.java
  src/main/java/ei/algobaroapi/domain/room_member/domain/RoomMember.java
  src/main/java/ei/algobaroapi/domain/room_member/domain/RoomMemberRepository.java
  src/main/java/ei/algobaroapi/domain/room_member/dto/request/HostChangeRequestDto.java
  src/main/java/ei/algobaroapi/domain/room_member/dto/response/RoomHostResponseDto.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/HostValidationException.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/OrganizerValidationException.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/RoomMemberNotFoundException.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/common/RoomMemberErrorCode.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/common/RoomMemberExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/room_member/service/RoomMemberService.java
  src/main/java/ei/algobaroapi/domain/room_member/service/RoomMemberServiceImpl.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/RoomControllerDoc.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/RoomMemberControllerDoc.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/SolveControllerDoc.java
Labels: merge

#89 방 입장 시 검증해야 하는 로직 추가
  src/main/java/ei/algobaroapi/domain/room/domain/Room.java
  src/main/java/ei/algobaroapi/domain/room_member/controller/RoomMemberControllerDocImpl.java
  src/main/java/ei/algobaroapi/domain/room_member/dto/request/JoinRoomRequestDto.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/RoomMemberNotEnterException.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/common/RoomMemberErrorCode.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/common/RoomMemberExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/room_member/service/RoomMemberService.java
  src/main/java/ei/algobaroapi/domain/room_member/service/RoomMemberServiceImpl.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/RoomMemberControllerDoc.java
Labels: refactor, feat

#90 dev -> main
  src/main/java/ei/algobaroapi/domain/room/controller/RoomControllerDocImpl.java
  src/main/java/ei/algobaroapi/domain/room/domain/Room.java
  src/main/java/ei/algobaroapi/domain/room/domain/RoomRepository.java
  src/main/java/ei/algobaroapi/domain/room/domain/RoomRepositoryQuery.java
  src/main/java/ei/algobaroapi/domain/room/domain/RoomRepositoryQueryImpl.java
  src/main/java/ei/algobaroapi/domain/room/dto/request/RoomListRequestDto.java
  src/main/java/ei/algobaroapi/domain/room/dto/response/RoomResponseDto.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomService.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomServiceImpl.java
  src/main/java/ei/algobaroapi/domain/room_member/controller/RoomMemberControllerDocImpl.java
  src/main/java/ei/algobaroapi/domain/room_member/domain/RoomMemberRepository.java
  src/main/java/ei/algobaroapi/domain/room_member/dto/request/JoinRoomRequestDto.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/RoomMemberNotEnterException.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/RoomMemberNotReadyException.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/common/RoomMemberErrorCode.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/common/RoomMemberExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/room_member/service/RoomMemberService.java
  src/main/java/ei/algobaroapi/domain/room_member/service/RoomMemberServiceImpl.java
  src/main/java/ei/algobaroapi/domain/solve/controller/SolveController.java
  src/main/java/ei/algobaroapi/domain/solve/domain/SolveHistory.java
  src/main/java/ei/algobaroapi/domain/solve/domain/SolveHistoryRepositoryQueryImpl.java
  src/main/java/ei/algobaroapi/domain/solve/dto/request/SolveHistoryListFindRequest.java
  src/main/java/ei/algobaroapi/domain/solve/dto/response/SolveHistoryDetailResponse.java
  src/main/java/ei/algobaroapi/domain/solve/dto/response/SolveHistoryResponse.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryService.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryServiceImpl.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/RoomControllerDoc.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/RoomMemberControllerDoc.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/SolveControllerDoc.java
  src/main/java/ei/algobaroapi/global/dto/PageResponse.java
Labels: merge

#98 dev -> main
  .gitignore
  build.gradle
  src/main/java/ei/algobaroapi/domain/chat/controller/ChatMessageController.java
  src/main/java/ei/algobaroapi/domain/chat/dto/MessageRequest.java
  src/main/java/ei/algobaroapi/domain/chat/dto/MessageResponse.java
  src/main/java/ei/algobaroapi/domain/chat/dto/MessageType.java
  src/main/java/ei/algobaroapi/domain/chat/service/ChatService.java
  src/main/java/ei/algobaroapi/domain/chat/service/ChatServiceImpl.java
  src/main/java/ei/algobaroapi/domain/chat/service/MessageService.java
  src/main/java/ei/algobaroapi/domain/chat/service/MessageServiceImpl.java
  src/main/java/ei/algobaroapi/domain/member/controller/MemberController.java
  src/main/java/ei/algobaroapi/domain/member/domain/Member.java
  src/main/java/ei/algobaroapi/domain/member/dto/request/MemberGeneralUpdateRequest.java
  src/main/java/ei/algobaroapi/domain/member/dto/request/MemberPasswordUpdateRequest.java
  src/main/java/ei/algobaroapi/domain/member/service/MemberService.java
  src/main/java/ei/algobaroapi/domain/member/service/MemberServiceImpl.java
  src/main/java/ei/algobaroapi/domain/room/controller/RoomControllerDocImpl.java
  src/main/java/ei/algobaroapi/domain/room/domain/Room.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomService.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomServiceImpl.java
  src/main/java/ei/algobaroapi/domain/room_member/controller/RoomMemberControllerDocImpl.java
  src/main/java/ei/algobaroapi/domain/room_member/domain/RoomMember.java
  src/main/java/ei/algobaroapi/domain/room_member/dto/request/HostManualChangeRequestDto.java
  src/main/java/ei/algobaroapi/domain/room_member/dto/response/RoomExitResponse.java
  src/main/java/ei/algobaroapi/domain/room_member/dto/response/RoomHostAutoChangeResponseDto.java
  src/main/java/ei/algobaroapi/domain/room_member/dto/response/RoomHostManualResponseDto.java
  src/main/java/ei/algobaroapi/domain/room_member/service/RoomMemberService.java
  src/main/java/ei/algobaroapi/domain/room_member/service/RoomMemberServiceImpl.java
  src/main/java/ei/algobaroapi/domain/solve/controller/SolveController.java
  src/main/java/ei/algobaroapi/domain/solve/dto/response/SolveHistoryResponse.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryService.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryServiceImpl.java
  src/main/java/ei/algobaroapi/global/config/S3Config.java
  src/main/java/ei/algobaroapi/global/config/SwaggerConfig.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/MemberControllerDoc.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/RoomMemberControllerDoc.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/SolveControllerDoc.java
  src/main/java/ei/algobaroapi/global/exception/S3Exception.java
  src/main/java/ei/algobaroapi/global/exception/common/GlobalErrorCode.java
  src/main/java/ei/algobaroapi/global/exception/common/GlobalExceptionHandler.java
  src/main/java/ei/algobaroapi/global/jwt/JwtProvider.java
  src/main/java/ei/algobaroapi/global/socket/WebSocketChannelInterceptor.java
  src/main/java/ei/algobaroapi/global/util/S3Util.java
Labels: merge

#101 dev -> main
  src/main/java/ei/algobaroapi/domain/compile/dto/response/JdoodleCompileResponse.java
  src/main/java/ei/algobaroapi/domain/member/controller/MemberController.java
  src/main/java/ei/algobaroapi/domain/member/domain/Member.java
  src/main/java/ei/algobaroapi/domain/member/service/MemberService.java
  src/main/java/ei/algobaroapi/domain/member/service/MemberServiceImpl.java
  src/main/java/ei/algobaroapi/domain/room_member/controller/RoomMemberControllerDocImpl.java
  src/main/java/ei/algobaroapi/domain/room_member/dto/response/RoomHostManualResponseDto.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/OrganizerValidationException.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/common/RoomMemberExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/room_member/service/RoomMemberService.java
  src/main/java/ei/algobaroapi/domain/solve/domain/SolveHistoryRepositoryQuery.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryServiceImpl.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/MemberControllerDoc.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/RoomMemberControllerDoc.java
  src/main/java/ei/algobaroapi/global/exception/common/GlobalErrorCode.java
  src/main/java/ei/algobaroapi/global/util/S3Util.java
Labels: merge

#103 방 정보 조회 시 member id도 같이 반환하도록 변경
  src/main/java/ei/algobaroapi/domain/room_member/dto/response/RoomMemberResponseDto.java
Labels: mod

#104 dev -> main
  src/main/java/ei/algobaroapi/domain/room_member/dto/response/RoomMemberResponseDto.java
Labels: merge

#109 dev -> main
  src/main/java/ei/algobaroapi/domain/room/domain/RoomRepositoryQueryImpl.java
  src/main/java/ei/algobaroapi/domain/room/dto/response/RoomDetailResponseDto.java
  src/main/java/ei/algobaroapi/domain/solve/domain/SolveHistoryRepositoryQueryImpl.java
Labels: merge

#110 dev -> main
  src/main/java/ei/algobaroapi/domain/problem/controller/ProblemController.java
  src/main/java/ei/algobaroapi/domain/problem/service/BojProblemServiceImpl.java
  src/main/java/ei/algobaroapi/domain/problem/service/ProblemService.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/ProblemControllerDoc.java
Labels: merge

#115 dev -> main
  src/main/java/ei/algobaroapi/domain/compile/dto/request/CompileExecutionRequest.java
  src/main/java/ei/algobaroapi/domain/room/controller/RoomControllerDocImpl.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomService.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomServiceImpl.java
  src/main/java/ei/algobaroapi/domain/solve/controller/SolveController.java
  src/main/java/ei/algobaroapi/domain/solve/domain/SolveHistoryRepository.java
  src/main/java/ei/algobaroapi/domain/solve/dto/request/BojCodeSubmissionRequest.java
  src/main/java/ei/algobaroapi/domain/solve/service/BojSolveServiceImpl.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryService.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryServiceImpl.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/RoomControllerDoc.java
Labels: merge

#117 소켓 코드 풀이 시작 시 메시지 반환 값에 종료 시간 포함하도록 변경
  src/main/java/ei/algobaroapi/domain/chat/dto/MessageResponse.java
  src/main/java/ei/algobaroapi/domain/chat/service/ChatServiceImpl.java
Labels: mod

#118 dev -> main
  src/main/java/ei/algobaroapi/domain/chat/dto/MessageResponse.java
  src/main/java/ei/algobaroapi/domain/chat/service/ChatServiceImpl.java
Labels: merge

#120 Room List 조회 시 언어 필터링 오류 수정 및 0명인 방 노출되지 않도록 변경
  src/main/java/ei/algobaroapi/domain/room/domain/RoomRepositoryQueryImpl.java
Labels: bug, mod

#126 dev -> main
  src/main/java/ei/algobaroapi/domain/compile/dto/response/CompileExecutionResponse.java
  src/main/java/ei/algobaroapi/domain/compile/dto/response/JdoodleCompileResponse.java
  src/main/java/ei/algobaroapi/domain/compile/exception/JdoodleException.java
  src/main/java/ei/algobaroapi/domain/compile/exception/common/CompileErrorCode.java
  src/main/java/ei/algobaroapi/domain/compile/exception/common/CompileExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/compile/service/JdoodleCompileServiceImpl.java
  src/main/java/ei/algobaroapi/domain/room/domain/RoomRepositoryQueryImpl.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/CompileControllerDoc.java
Labels: merge

#128 dev -> main
  src/main/java/ei/algobaroapi/global/exception/common/GlobalExceptionHandler.java
Labels: merge

#129 배포 환경에서 커스텀 오류 대신 500 null 에러 발생하는 오류 수정
  src/main/java/ei/algobaroapi/global/exception/common/GlobalExceptionHandler.java
Labels: bug

#130 dev -> main
  src/main/java/ei/algobaroapi/global/exception/common/GlobalExceptionHandler.java
Labels: merge

#131 배포 환경에서 커스텀 오류 대신 500 null 에러 발생하는 오류 수정
  src/main/java/ei/algobaroapi/domain/auth/exception/common/AuthExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/compile/exception/common/CompileExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/member/exception/common/MemberExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/problem/exception/common/ProblemExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/room/exception/common/RoomExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/room_member/exception/common/RoomMemberExceptionHandler.java
  src/main/java/ei/algobaroapi/global/exception/common/GlobalExceptionHandler.java
Labels: bug

#138 dev -> main
  src/main/java/ei/algobaroapi/domain/chat/service/ChatServiceImpl.java
  src/main/java/ei/algobaroapi/domain/room/controller/RoomControllerDocImpl.java
  src/main/java/ei/algobaroapi/domain/room/domain/Room.java
  src/main/java/ei/algobaroapi/domain/room/domain/RoomRepository.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomService.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomServiceImpl.java
  src/main/java/ei/algobaroapi/domain/room_member/domain/RoomMember.java
  src/main/java/ei/algobaroapi/domain/room_member/service/RoomMemberService.java
  src/main/java/ei/algobaroapi/domain/room_member/service/RoomMemberServiceImpl.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryServiceImpl.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/RoomControllerDoc.java
Labels: merge

#140 방 입장 퇴장 시 해당 멤버의 닉네임 value 값에 추가
  src/main/java/ei/algobaroapi/domain/chat/dto/MessageResponse.java
  src/main/java/ei/algobaroapi/domain/chat/service/ChatServiceImpl.java
Labels: mod

#141 방 정보 조회 시 problemLink를 반환하도록 필드 추가
  src/main/java/ei/algobaroapi/domain/room/dto/response/RoomDetailResponseDto.java
  src/main/java/ei/algobaroapi/domain/room/dto/response/RoomResponseDto.java
Labels: bug, feat

#142 dev -> main
  src/main/java/ei/algobaroapi/domain/chat/dto/MessageResponse.java
  src/main/java/ei/algobaroapi/domain/chat/service/ChatServiceImpl.java
  src/main/java/ei/algobaroapi/domain/room/dto/response/RoomDetailResponseDto.java
  src/main/java/ei/algobaroapi/domain/room/dto/response/RoomResponseDto.java
Labels: merge

#146 소켓 end-coding 요청 시 작동하지 않는 오류 수정
  src/main/java/ei/algobaroapi/domain/problem/service/BojProblemServiceImpl.java
Labels: bug, mod

#149 dev -> main
  src/main/java/ei/algobaroapi/domain/problem/service/BojProblemServiceImpl.java
  src/main/java/ei/algobaroapi/domain/room/controller/RoomControllerDocImpl.java
  src/main/java/ei/algobaroapi/domain/room/domain/Room.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomService.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomServiceImpl.java
  src/main/java/ei/algobaroapi/domain/solve/controller/SolveController.java
  src/main/java/ei/algobaroapi/domain/solve/dto/request/CodeSubmissionRequest.java
  src/main/java/ei/algobaroapi/domain/solve/dto/response/CodeSubmissionResponse.java
  src/main/java/ei/algobaroapi/domain/solve/service/BojSolveServiceImpl.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveService.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/SolveControllerDoc.java
Labels: merge

#153 end-coding 권한 체크 삭제
  src/main/java/ei/algobaroapi/domain/chat/service/ChatServiceImpl.java
Labels: mod

#155 dev -> main
  src/main/java/ei/algobaroapi/domain/chat/service/ChatServiceImpl.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomService.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomServiceImpl.java
  src/main/java/ei/algobaroapi/domain/solve/domain/SolveHistory.java
  src/main/java/ei/algobaroapi/domain/solve/dto/request/BojCodeSubmissionRequest.java
  src/main/java/ei/algobaroapi/domain/solve/dto/request/CodeSubmissionRequest.java
  src/main/java/ei/algobaroapi/domain/solve/service/BojSolveServiceImpl.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryService.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryServiceImpl.java
Labels: merge

#161 dev -> main
  src/main/java/ei/algobaroapi/AlgobaroApiApplication.java
  src/main/java/ei/algobaroapi/domain/room/controller/RoomControllerDocImpl.java
  src/main/java/ei/algobaroapi/domain/room/domain/Room.java
  src/main/java/ei/algobaroapi/domain/room/domain/RoomRepository.java
  src/main/java/ei/algobaroapi/domain/room/dto/request/RoomUpdateRequestDto.java
  src/main/java/ei/algobaroapi/domain/room/dto/response/RoomDetailResponseDto.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomSchedulerService.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomSchedulerServiceImpl.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomService.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomServiceImpl.java
  src/main/java/ei/algobaroapi/domain/solve/domain/SolveHistory.java
  src/main/java/ei/algobaroapi/domain/solve/dto/request/BojCodeSubmissionRequest.java
  src/main/java/ei/algobaroapi/domain/solve/dto/request/CodeSubmissionRequest.java
  src/main/java/ei/algobaroapi/domain/solve/dto/response/SolveHistoryDetailResponse.java
  src/main/java/ei/algobaroapi/domain/solve/dto/response/SolveHistoryResponse.java
  src/main/java/ei/algobaroapi/domain/solve/dto/response/SolveResult.java
  src/main/java/ei/algobaroapi/domain/solve/service/BojSolveServiceImpl.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryService.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryServiceImpl.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/RoomControllerDoc.java
Labels: merge

#162 dev -> main
  src/main/java/ei/algobaroapi/domain/room/dto/response/RoomDetailResponseDto.java
Labels: merge

#163 dev -> main
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryServiceImpl.java
Labels: merge

#165 이미 사용중인 닉네임에 대한 예외처리 추가
  src/main/java/ei/algobaroapi/domain/member/exception/common/MemberErrorCode.java
  src/main/java/ei/algobaroapi/domain/member/service/MemberServiceImpl.java
Labels: feat

#167 dev -> main
  README.md
  src/main/java/ei/algobaroapi/domain/member/exception/common/MemberErrorCode.java
  src/main/java/ei/algobaroapi/domain/member/service/MemberServiceImpl.java
Labels: merge
