Repository 1e5i-Shark/algobaro-api, pull requests merged in 2024-02, with the labels that each got.

#2 infra: CI 세팅
  .github/workflows/gradle.yml
Labels: infra

#3 dev -> main
  .github/ISSUE_TEMPLATE/-etc.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/ei/algobaroapi/AlgobaroApiApplication.java
  src/main/java/ei/algobaroapi/domain/auth/controller/AuthController.java
  src/main/java/ei/algobaroapi/domain/auth/dto/AuthSignInRequest.java
  src/main/java/ei/algobaroapi/domain/auth/dto/AuthSignInResponse.java
  src/main/java/ei/algobaroapi/domain/auth/dto/AuthSignUpRequest.java
  src/main/java/ei/algobaroapi/domain/auth/exception/AuthPasswordException.java
  src/main/java/ei/algobaroapi/domain/auth/exception/common/AuthErrorCode.java
  src/main/java/ei/algobaroapi/domain/auth/exception/common/AuthExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/auth/service/AuthService.java
  src/main/java/ei/algobaroapi/domain/auth/util/PasswordUtil.java
  src/main/java/ei/algobaroapi/domain/member/domain/Member.java
  src/main/java/ei/algobaroapi/domain/member/domain/MemberRepository.java
  src/main/java/ei/algobaroapi/domain/member/domain/vo/EmailVo.java
  src/main/java/ei/algobaroapi/domain/member/exception/MemberFoundException.java
  src/main/java/ei/algobaroapi/domain/member/exception/common/MemberErrorCode.java
  src/main/java/ei/algobaroapi/domain/member/exception/common/MemberExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/member/service/MemberService.java
  src/main/java/ei/algobaroapi/global/config/PasswordEncoderConfig.java
  src/main/java/ei/algobaroapi/global/config/QueryDslConfig.java
  src/main/java/ei/algobaroapi/global/config/SwaggerConfig.java
  src/main/java/ei/algobaroapi/global/config/WebSecurityConfig.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/AuthControllerDoc.java
  src/main/java/ei/algobaroapi/global/entity/BaseEntity.java
  src/main/java/ei/algobaroapi/global/exception/GlobalExceptionHandler.java
  src/main/java/ei/algobaroapi/global/jwt/JwtAuthenticationFilter.java
  src/main/java/ei/algobaroapi/global/jwt/JwtProvider.java
  src/main/java/ei/algobaroapi/global/jwt/UserDetailServiceImpl.java
  src/main/java/ei/algobaroapi/global/response/ResponseAdvice.java
  src/main/java/ei/algobaroapi/global/response/ResponseUtil.java
  src/main/java/ei/algobaroapi/global/response/message/BasicResponse.java
  src/main/java/ei/algobaroapi/global/response/message/ErrorResponse.java
  src/main/resources/application.properties
  src/test/java/e5i/algobaroapi/AlgobaroApiApplicationTests.java
  src/test/java/ei/algobaroapi/AlgobaroApiApplicationTest.java
  src/test/resources/application.properties
Labels: merge

#4 fix: CD workflow를 위한 파일 생성
  src/main/resources/application-prod.properties
Labels: merge

#5 dev -> main
  .github/workflows/cd.yml
  src/main/resources/application.properties
Labels: merge

#6 dev -> main
  .github/workflows/cd.yml
Labels: merge

#7 dev -> main
  .github/workflows/cd.yml
Labels: merge

#8 dev -> main
  .github/workflows/cd.yml
Labels: merge

#10 dev -> main
  .github/workflows/cd.yml
  src/main/resources/application.properties
Labels: merge

#11 dev -> main
  src/main/java/ei/algobaroapi/domain/auth/controller/AuthController.java
  src/main/java/ei/algobaroapi/domain/auth/dto/AuthSignInRequest.java
  src/main/java/ei/algobaroapi/domain/auth/dto/AuthSignInResponse.java
  src/main/java/ei/algobaroapi/domain/auth/dto/AuthSignUpRequest.java
  src/main/java/ei/algobaroapi/domain/auth/exception/common/AuthErrorCode.java
  src/main/java/ei/algobaroapi/domain/auth/exception/common/AuthExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/member/exception/common/MemberErrorCode.java
  src/main/java/ei/algobaroapi/domain/member/exception/common/MemberExceptionHandler.java
  src/main/java/ei/algobaroapi/global/config/WebSecurityConfig.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/AuthControllerDoc.java
  src/main/java/ei/algobaroapi/global/exception/GlobalExceptionHandler.java
  src/main/java/ei/algobaroapi/global/response/message/ErrorResponse.java
Labels: merge

#23 PR 템플릿 수정(사용하지 않는 부분 삭제, 개행 추가)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: doc s

#45 dev -> main
  src/main/java/ei/algobaroapi/domain/solve/controller/SolveController.java
  src/main/java/ei/algobaroapi/domain/solve/domain/SolveHistoryRepository.java
  src/main/java/ei/algobaroapi/domain/solve/domain/SolveHistoryRepositoryQuery.java
  src/main/java/ei/algobaroapi/domain/solve/domain/SolveHistoryRepositoryQueryImpl.java
  src/main/java/ei/algobaroapi/domain/solve/dto/request/SolveHistoryListFindRequest.java
  src/main/java/ei/algobaroapi/domain/solve/dto/response/SolveHistoryDetailResponse.java
  src/main/java/ei/algobaroapi/domain/solve/exception/SolveAccessException.java
  src/main/java/ei/algobaroapi/domain/solve/exception/SolveFoundException.java
  src/main/java/ei/algobaroapi/domain/solve/exception/common/SolveErrorCode.java
  src/main/java/ei/algobaroapi/domain/solve/exception/common/SolveExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/solve/service/BojSolveServiceImpl.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryService.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryServiceImpl.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveService.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/SolveControllerDoc.java
Labels: merge

#47 CORS 모두 허용하도록 변경
  src/main/java/ei/algobaroapi/global/config/WebSecurityConfig.java
Labels: feat

#49 dev -> main
  src/main/java/ei/algobaroapi/domain/auth/controller/AuthController.java
  src/main/java/ei/algobaroapi/domain/auth/dto/request/AuthSignInRequest.java
  src/main/java/ei/algobaroapi/domain/auth/dto/request/AuthSignUpRequest.java
  src/main/java/ei/algobaroapi/domain/auth/dto/response/AuthSignInResponse.java
  src/main/java/ei/algobaroapi/domain/auth/dto/response/AuthSignUpResponse.java
  src/main/java/ei/algobaroapi/domain/auth/exception/AuthEmailExistenceException.java
  src/main/java/ei/algobaroapi/domain/auth/exception/AuthNicknameExistenceException.java
  src/main/java/ei/algobaroapi/domain/auth/exception/common/AuthErrorCode.java
  src/main/java/ei/algobaroapi/domain/auth/exception/common/AuthExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/auth/service/AuthService.java
  src/main/java/ei/algobaroapi/domain/member/domain/Member.java
  src/main/java/ei/algobaroapi/domain/member/domain/MemberRepository.java
  src/main/java/ei/algobaroapi/domain/member/domain/vo/EmailVo.java
  src/main/java/ei/algobaroapi/domain/member/service/MemberService.java
  src/main/java/ei/algobaroapi/domain/member/service/MemberServiceImpl.java
  src/main/java/ei/algobaroapi/domain/room/controller/RoomControllerDocImpl.java
  src/main/java/ei/algobaroapi/domain/room/domain/Room.java
  src/main/java/ei/algobaroapi/domain/room/domain/RoomRepository.java
  src/main/java/ei/algobaroapi/domain/room/dto/request/RoomCreateRequestDto.java
  src/main/java/ei/algobaroapi/domain/room/dto/request/RoomListRequestDto.java
  src/main/java/ei/algobaroapi/domain/room/dto/request/RoomUpdateRequestDto.java
  src/main/java/ei/algobaroapi/domain/room/dto/response/RoomDetailResponseDto.java
  src/main/java/ei/algobaroapi/domain/room/exception/RoomNotFoundException.java
  src/main/java/ei/algobaroapi/domain/room/exception/common/RoomErrorCode.java
  src/main/java/ei/algobaroapi/domain/room/exception/common/RoomExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomService.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomServiceImpl.java
  src/main/java/ei/algobaroapi/global/config/WebSecurityConfig.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/AuthControllerDoc.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/RoomControllerDoc.java
Labels: merge

#50 dev -> main
  src/main/java/ei/algobaroapi/global/config/WebSecurityConfig.java
Labels: merge

#53 dev -> main
  src/main/java/ei/algobaroapi/global/config/WebSecurityConfig.java
Labels: merge

#52 풀이 종료 후 방 인원 제출 코드 리스트 조회 기능 구현
  src/main/java/ei/algobaroapi/domain/auth/controller/AuthController.java
  src/main/java/ei/algobaroapi/domain/auth/exception/common/AuthExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/member/service/MemberService.java
  src/main/java/ei/algobaroapi/domain/problem/dto/request/ProblemSolveRequest.java
  src/main/java/ei/algobaroapi/domain/problem/service/BojProblemServiceImpl.java
  src/main/java/ei/algobaroapi/domain/problem/service/ProblemService.java
  src/main/java/ei/algobaroapi/domain/room/exception/common/RoomExceptionHandler.java
  src/main/java/ei/algobaroapi/domain/solve/controller/SolveController.java
  src/main/java/ei/algobaroapi/domain/solve/domain/SolveHistory.java
  src/main/java/ei/algobaroapi/domain/solve/domain/SolveHistoryRepository.java
  src/main/java/ei/algobaroapi/domain/solve/dto/response/SolveResult.java
  src/main/java/ei/algobaroapi/domain/solve/dto/response/SolveResultResponse.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryService.java
  src/main/java/ei/algobaroapi/domain/solve/service/SolveHistoryServiceImpl.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/AuthControllerDoc.java
  src/main/java/ei/algobaroapi/global/config/swaggerdoc/SolveControllerDoc.java
Labels: feat

#57 결과 조회를 위한 크롤링 코드 작성
  src/main/java/ei/algobaroapi/domain/problem/service/BojProblemServiceImpl.java
Labels: feat

#59 dev -> main
  src/main/java/ei/algobaroapi/domain/room/domain/RoomRepository.java
  src/main/java/ei/algobaroapi/domain/room/service/RoomServiceImpl.java
  src/main/java/ei/algobaroapi/domain/room_member/controller/RoomMemberControllerDocImpl.java
Labels: bug, merge

#61 스웨거 상으로 발생하는 오류 해결
  src/main/java/ei/algobaroapi/domain/room/dto/request/RoomCreateRequestDto.java
  src/main/java/ei/algobaroapi/domain/room/dto/request/RoomUpdateRequestDto.java
  src/main/java/ei/algobaroapi/domain/room/dto/response/RoomDetailResponseDto.java
Labels: bug

#62 fix #60: 스웨거 상으로 발생하는 오류 해결
  src/main/java/ei/algobaroapi/domain/room/dto/request/RoomCreateRequestDto.java
  src/main/java/ei/algobaroapi/domain/room/dto/request/RoomUpdateRequestDto.java
  src/main/java/ei/algobaroapi/domain/room/dto/response/RoomDetailResponseDto.java
Labels: merge
